version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
      command: |
        systemctl restart apache2.service
