version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: inline
      timeout: 300
      runas: root
      command: |
        rm -rf /var/www/html/*
        # Ensure directory exists
        mkdir -p /var/www/html
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
      command: |
        systemctl restart apache2.service
